apps/marketer/urls.py
from django.urls import path
from .views import *

app_name = 'marketer'

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('engagements/', engagements, name='engagements'),
    path('partners/', partners, name='partners'),
    path('add-partner/', add_partner, name='add-partner'),
]

apps/partner/urls.py
from django.urls import path
from .views import *

app_name = 'partner'


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('coupons/', coupons, name='coupons'),
    path('commissions/', commissions, name='commissions'),
    path('coupons-search/', search_coupons, name='coupons_search')
]

apps/patient/urls.py
from django.urls import path
from .views import *

app_name = 'patient'


urlpatterns = [
    path('search/', search, name='search'),
    path('add/', add, name='add'),
    path('all/', patients, name='all'),
    path('<uuid>/', patient_details, name='details'),
]

apps/schedule/urls.py
from django.urls import path
from .views import *
app_name = 'schedule'


urlpatterns = [
    path('weekly/', weekly, name='weekly'),
    path('daily/', daily, name='daily'),
    path('<uuid>/', planner_details, name='details'),
]

rabito_crm/urls.py
from apps.user.views import permission_error, user_login, user_logout
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from apps.user import urls as user_urls
from apps.patient import urls as patient_urls
from apps.feedback import urls as feedback_urls
from apps.commission import urls as commission_urls
from apps.marketer import urls as marketer_urls
from apps.schedule import urls as schedule_urls
from apps.partner import urls as partner_urls


def layout(request):
    return render(request, 'crm/layout.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include(user_urls, namespace="user")),
    path('patient/', include(patient_urls, namespace="patient")),
    path('feedback/', include(feedback_urls, namespace="feedback")),
    path('commission/', include(commission_urls, namespace="commission")),
    path('marketer/', include(marketer_urls, namespace="marketer")),
    path('partner/', include(partner_urls, namespace="partner")),
    path('planner/', include(schedule_urls, namespace="schedule")),
    path('permission-error/', permission_error, name="permission-error"),
    path('', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

apps/marketer/models.py
from django.db import models

# Create your models here.

apps/partner/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.


class Partner(models.Model):
    partner_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='partner', blank=True, null=True, on_delete=models.DO_NOTHING)
    workplace = models.CharField(max_length=300, blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='partners', on_delete=models.DO_NOTHING)
    code = models.CharField(max_length=100, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=100)
    branch_code = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="feedbacks", on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'partner_bio'
        managed = True
        verbose_name = 'Partner'
        verbose_name_plural = 'Partners'
    
    def __str__(self):
        return self.workplace


COUPON_STATUS = [
    (1, 'Generated'),
    (2, 'Admitted'),
    # (3, ''),
    (3, 'Approved'),
    (4, 'Cancelled')
]


class Coupon(models.Model):
    code = models.CharField(max_length=100, blank=True, null=True)
    patient_first_name = models.CharField(max_length=100, blank=True, null=True)
    patient_last_name = models.CharField(max_length=100, blank=True, null=True)
    patient_phone_number = models.CharField(max_length=100, blank=True, null=True)
    patient_dob = models.DateField(blank=True, null=True)
    commission = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="coupons", on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(default=timezone.now)
    branch_code = models.CharField(max_length=100, blank=True, null=True)
    status = models.IntegerField(choices=COUPON_STATUS, blank=True, null=True)
    
    class Meta:
        db_table = 'coupon'
        managed = True
        verbose_name = 'Coupon'
        verbose_name_plural = 'Coupons'

    def __str__(self):
        return self.code


class CouponStatus(models.Model):
    coupon = models.ForeignKey(Coupon, on_delete=models.DO_NOTHING, related_name='coupon_status_coupon', blank=True, null=True)
    status = models.IntegerField(choices=COUPON_STATUS, blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="coupon_statuses", on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'coupon_status'
        managed = True
        verbose_name = 'Coupon Status'
        verbose_name_plural = 'Coupon Statuses'

    def __str__(self):
        return str(self.get_status_display())

apps/schedule/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
import uuid
# Create your models here.


ACTIVITY_TYPES = [
    ("Individual", "Individual"),
    ("Joint", "Joint"),
    ("Group", "Group")
]

class Planner(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4)
    # activity_type = models.CharField(max_length=100, blank=True, null=True, choices=ACTIVITY_TYPES)
    # joint_with = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name="joint_with_planner", blank=True, null=True)
    group = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="group_planner", blank=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    activity_date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    orignal_date = models.DateField(null=True, blank=True)
    original_start_time = models.TimeField(null=True, blank=True)
    original_end_time = models.TimeField(blank=True, null=True)
    report = models.CharField(max_length=500, blank=True, null=True)
    is_rescheduled = models.BooleanField(default=False)
    reschedule_at = models.DateTimeField(blank=True, null=True)
    reschedule_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="reschedule_planners", blank=True, null=True, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="planners", on_delete=models.DO_NOTHING)
    comments = models.ManyToManyField('Comment', related_name="comments_planner", blank=True)

    class Meta:
        db_table = 'planner'
        managed = True
        verbose_name = 'Planner'
        verbose_name_plural = 'Planners'

    def __str__(self):
        return self.description
    


class Engagement(models.Model):
    planner = models.ForeignKey(Planner, blank=True, null=True, related_name="planner_engagement", on_delete=models.DO_NOTHING)
    engaged_with = models.CharField(max_length=100, blank=True, null=True, choices=[('I', 'Individual'), ('C', 'Company')])
    contact_person = models.CharField(max_length=100, blank=True, null=True)
    full_name = models.CharField(max_length=200, blank=True, null=True)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="engagements", on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'engagement'
        managed = True
        verbose_name = 'Engagement'
        verbose_name_plural = 'Engagements'
        ordering = ('-created_at',)

    def __str__(self):
        return self.full_name
    


class Comment(models.Model):
    text = models.CharField(max_length=500, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="comments", on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'comment'
        managed = True
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.text
    

apps/user/models.py
from django.db import models

# Create your models here.

import uuid
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import Permission, PermissionsMixin
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, username, first_name, last_name, password=None, **extra_fields):
        if not username:
            raise ValueError('username is required')

        user = self.model(
            username=username,
            first_name=first_name,
            last_name=last_name
        )

        user.set_password(password)

        user.save(using=self._db)

        return user

    def create_superuser(self, username, first_name, last_name, password):
        user = self.create_user(username=username, first_name=first_name, last_name=last_name, password=password)
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.user_type = 'AD'
        user.save(using=self._db)
        return user


USER_TYPES = [
    ('AD', 'Admin User'),
    # ('NU', 'Nurse User'),
    ('PU', 'Partner User'),
    ('MAU', 'Marketing Admin User'),
    ('MU', 'Marketer User'),
    # ('AU', 'Account User'),
]


class User(AbstractBaseUser, PermissionsMixin):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, blank=True, null=True)
    code = models.CharField(max_length=100, blank=True, null=True)
    user_type = models.CharField(choices=USER_TYPES, max_length=100, blank=True, null=True)
    slug = models.SlugField(max_length=200, blank=True, null=True, unique=True)
    username = models.CharField(max_length=255, blank=True, null=True, unique=True)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True, blank=True, null=True)
    is_staff = models.BooleanField(default=False, blank=True, null=True)
    is_superuser = models.BooleanField(default=False, blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True,unique=True)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    profile = models.TextField(blank=True, null=True)
    gender = models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, blank=True, null=True)
    reset_password = models.BooleanField(blank=True, null=True)
    is_loggedin = models.BooleanField(blank=True, null=True)
    login_at = models.DateTimeField(blank=True, null=True)
    branch_code = models.CharField(max_length=255, blank=True, null=True)
    role = models.ForeignKey('Role', related_name="user_role", on_delete=models.DO_NOTHING, blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        db_table = 'user'
        ordering = ['-date_joined']

    def __str__(self):
        return f"{self.get_full_name()}"

    def has_role_perm(self, perm):

        if self.is_active and self.is_superuser:
            return True

        if not self.role:
            return False

        if perm:
            try:
                self.role.permissions.get(codename=perm)
                
                return True
            except Permission.DoesNotExist:         
                return False
        else: return False



class Role(models.Model):
    description = models.CharField(max_length=255, blank=True, null=True)
    permissions = models.ManyToManyField(
        Permission,
        related_name="role_permissions",
        verbose_name=_('role permissions'),
        blank=True,
    )
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, blank=True, null=True, related_name="roles", on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'role'
        managed = True
        verbose_name = 'Role'
        verbose_name_plural = 'Roles'

    def __str__(self):
        return str(self.description)

    def has_perm(self, perm):
        
        if perm:
            try:
                self.permissions.get(codename=perm)
                
                return True
            except Permission.DoesNotExist:         
                return False
        else: return False
        


REGIONS = [
    ('Ahafo', 'Ahafo'),
    ('Ashanti', 'Ashanti'),
    ('Bono East', 'Bono East'),
    ('Brong Ahafo', 'Brong Ahafo'),
    ('Central', 'Central'),
    ('Eastern', 'Eastern'),
    ('Greater Accra', 'Greater Accra'),
    ('North East', 'North East'),
    ('Northern', 'Northern'),
    ('Oti', 'Oti'),
    ('Savannah', 'Savannah'),
    ('Upper East', 'Upper East'),
    ('Western', 'Western'),
    ('Western North', 'Western North'),
    ('Volta', 'Volta')
]


class Branch(models.Model):
    slug = models.SlugField(max_length=200, blank=True, null=True, unique=True)
    code = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    region = models.CharField(max_length=255, blank=True, null=True, choices=REGIONS)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, blank=True, null=True, related_name="branches", on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'branch'
        managed = True
        verbose_name = 'Branch'
        verbose_name_plural = 'Branches'

    def __str__(self):
        return self.code
    

apps/marketer/views.py
from django.contrib import messages
from django.utils.text import slugify
from apps.user.models import User
from apps.partner.models import Partner
from apps.schedule.models import Engagement
from utils.decorators import marketer_required
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from utils import codes
# Create your views here.

@login_required(login_url='login')
@marketer_required(redirect_url='permission-error')
def dashboard(request):
    return render(request, 'marketers/dashboard.html')


@login_required(login_url='login')
@marketer_required(redirect_url='permission-error')
def engagements(request):

    context = {
        'object_list': Engagement.objects.filter(created_by=request.user)
    }

    return render(request, 'marketers/engagements.html', context)


@login_required(login_url='login')
@marketer_required(redirect_url='permission-error')
def partners(request):
    
    object_list = Partner.objects.filter(created_by=request.user)

    context = {
        'object_list': object_list
    }

    return render(request, 'marketers/partners.html', context)

@login_required(login_url='login')
@marketer_required(redirect_url='permission-error')
def add_partner(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        workplace = request.POST.get('workplace')
        location = request.POST.get('location')
        gender = request.POST.get('gender')

        try:
            User.objects.get(username=email)
            messages.error(request, 'User with this email already exists')
            return redirect('marketer:add-partner')
        except User.DoesNotExist:pass
        count = User.objects.count() + 1

        code = codes.user('{0:03}'.format(count), first_name, last_name)
        nu = User.objects.create(
            code=code,
            user_type='PU',
            username=email,
            email=email,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            gender=gender,
            branch_code=request.user.branch_code,
            slug="-".join([slugify(first_name), slugify(last_name)])
        )

        nu.set_password('password')

        nu.save()

        count = Partner.objects.count() + 1

        code = codes.partner('{0:03}'.format(count), workplace)

        np = Partner.objects.create(
            code=code,
            partner_user=nu,
            workplace=workplace,
            created_by=request.user,
            location=location,
            branch_code=request.user.branch_code,
        )

        return redirect('marketer:partners')

    return render(request, 'marketers/new_partner.html')

templates/marketers/daily.html
{% extends 'marketers/layout.html' %}
{% load schedule_tags %}
{% block title %}
Daily Planner
{% endblock title %}
{% block doc %}
active
{% endblock doc %}
{% block page_title %}
Daily Planner
{% endblock page_title %}
{% block content %}
<div class="row">
    <div class="col-md-8 col-lg-8 col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-9 col-lg-9">
                        <h5>{{today.date}}</h5>
                    </div>
                    <div class="col-md-3 col-lg-3" align="right">
                        <a href="{% url 'schedule:weekly' %}" class="btn btn-sm btn-default"><span class='h5'>Weekly</span></a> 
                        <a href="?date={{pdate}}" class="btn btn-default border-0">
                            <i class="fa fa-1x fa-chevron-left"></i>
                        </a>
                        <a href="?date={{ndate}}" class="btn btn-default border-0">
                            <i class="fa fa-1x fa-chevron-right"></i>
                        </a>
                    </div>
                </div>
                
            </div>
            <div class="card-body">
                <div class="list-group-flush">
                    {% for hour in hours %}
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-1 col-lg-1 col-sm-2 col-2">
                                {{hour}}
                            </div>
                            <div class="col-md-11 col-lg-11 col-sm-10 col-10">
                                {% hourly_planners hour today.date user as planners %}
                                {% for planner in planners.planners %}
                                    <div class="p-1 m-0 mb-2" style="border-left: 2px dashed rgba(1, 213, 250, 0.705); background-color: lightcyan">
                                        <a href="{% url 'schedule:details' planner.uuid %}">
                                            {{planner.description}} - {{planner.start_time}} to {{planner.end_time}}
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-lg-4 col-sm-12 bg-white pt-2 mb-5">
        <div align="center" class="m-5">
            <i class="fa text-primary fa-9x fa-calendar-plus"></i>
        </div>
        <form action="" method="post">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Error!</h5>
                {{message}}
            </div>
            {% endfor %}
            {% endif %}

            {% csrf_token %}
            
            <div class="form-group">
                <input type="text" name="description" required placeholder="Title" id=""
                    class="form-control bg-transparent form-control-lg">
            </div>
            <div class="form-group">
                <input type="text" required id="id_date" value="{{today.date | safe}}" name='date' placeholder='Date'
                    autocomplete="off" data-toggle="datetimepicker" data-target="#id_date"
                    class="form-control form-control-lg datetimepicker-input">
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <input type="text" required placeholder='From' value="{{time}}" autocomplete="off"
                                name='start' id="id_starts" class="form-control form-control-lg datetimepicker-input"
                                data-toggle="datetimepicker" data-target="#id_starts">
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <input type="text" required placeholder='To' autocomplete="off" name='end' id="id_ends"
                                class="form-control form-control-lg datetimepicker-input" data-toggle="datetimepicker"
                                data-target="#id_ends">
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>Invite Others</label>
                <select name='members' class="select2 custom-select form-control form-control-lg" multiple="multiple"
                    data-placeholder="Select people to Invite" style="width: 100%;">
                    {% for member in members %}
                    <option value="{{member.uuid}}">{{member.get_full_name}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group" align="right">
                <button class="btn-primary btn">Schedule</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}
{% block js %}
<script>
    $(function () {
        $('[data-mask]').inputmask()
        //Date picker
        $('#id_date').datetimepicker({
            format: 'YYYY-MM-DD'
        });
        $('#id_starts').datetimepicker({
            format: 'HH:mm A'
        });
        $('#id_ends').datetimepicker({
            format: 'HH:mm A'
        });
        //Initialize Select2 Elements
        $('.select2').select2()
        // $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });
    });

</script>
{% endblock js %}

templates/marketers/dashboard.html
{% extends 'marketers/layout.html' %}
{% block title %}Dashboard{% endblock title %}

templates/marketers/engagements.html
{% extends 'marketers/layout.html' %}
{% load schedule_tags %}
{% block title %}
My Engagements
{% endblock title %}
{% block engage %}
active
{% endblock %}
{% block page_title %}
My Engagements
{% endblock page_title %}
{% block content %}
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th nowrap>Individual / Company</th>
                        <th nowrap>Full Name / Company Name</th>
                        <th nowrap>Contact Person</th>
                        <th nowrap>Phone Number</th>
                        <th nowrap>Email</th>
                        <th nowrap>Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td nowrap>{{object.get_engaged_with_display}}</td>
                            <td nowrap>{{object.full_name}}</td>
                            <td nowrap>{{object.contact_person}}</td>
                            <td nowrap>{{object.phone_number}}</td>
                            <td nowrap>{{object.email}}</td>
                            <td nowrap>{{object.created_at}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/marketers/new_partner.html
{% extends 'marketers/layout.html' %}
{% load schedule_tags %}
{% block title %}
Add Partner
{% endblock title %}
{% block part %}
active
{% endblock %}
{% block page_title %}
Add Partner
{% endblock page_title %}
{% block content %}
<div class="card">
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_workplace">Workplace</label>
                <input type="text" required name="workplace" placeholder="Enter partner workplace" id="id_workplace" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="id_location">Location</label>
                <input type="text" required name="location" placeholder="Enter workplace location" id="id_location" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="id_first">First Name</label>
                <input type="text" required name="first_name" placeholder="Enter first name" id="id_first" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="id_last">Last Name</label>
                <input type="text" required name="last_name" placeholder="Enter last name" id="id_last" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="id_email">Email Address</label>
                <input type="email" name="email" required placeholder="Enter email address" id="id_email" class="form-control form-control-sm">
                <small>This will be used to login on the partner portal</small>
            </div>
            <div class="form-group">
                <label for="id_phone">Phone Number</label>
                <input type="text" required name="phone_number" placeholder="Enter phone number" id="id_phone" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="id_gender">Gender</label>
                <select name="gender" required id="id_gender" class="custom-select">
                    <option value="">Select Gender</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/marketers/permission_error.html
{% extends 'marketers/layout.html' %}
{% block content %}
{% extends 'crm/layout.html' %}
{% block content %}
<div class="error-page">
    <h2 class="headline text-warning"> 403</h2>

    <div class="error-content">
        <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Permission needed here.</h3>

        <p>
            Happens that you do not have permission to view this resource.
            Meanwhile, you may <a href="{% url 'marketer:dashboard' %}">return to dashboard</a>.
        </p>

        <!-- <form class="search-form">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Search">

                <div class="input-group-append">
                    <button type="submit" name="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
            
        </form> -->
    </div>
    <!-- /.error-content -->
</div>
{% endblock content %}