apps/commission/urls.py
from django.urls import path

from . views import *

app_name = 'commissiion'

urlpatterns = [
    path('setups/', commission_setups, name='setups'),
    path('', all, name='all'),
    path('generated/', generated, name='generated'),
    path('confirmed/', confirmed, name='confirmed'),
    path('approved/', approved, name='approved'),
    path('canceled/', canceled, name='canceled'),
]

apps/feedback/urls.py
from django.urls import path
from .views import *

app_name = 'feedback'

urlpatterns = [
    path('setup/', setup, name="setup"),
    path('add-setup/', add_setup, name="add-setup"),
    path('responses/', feedback_responses, name="responses"),
    path('response/<uuid>/', response_details, name="response-details"),
    path('setup-details/<uuid>/', setup_details, name="setup-details"),
]

apps/patient/urls.py
from django.urls import path
from .views import *

app_name = 'patient'


urlpatterns = [
    path('search/', search, name='search'),
    path('add/', add, name='add'),
    path('all/', patients, name='all'),
    path('<uuid>/', patient_details, name='details'),
]

apps/user/urls.py
from django.urls import path
from .views import *
# from django.views.defaults import permission_denied

app_name = 'user'

urlpatterns = [
    # path('', user_login, name='login'),
    path('dashboard/', dashboard, name='dashboard'),
    path('branches/', branches, name='branches'),
    path('roles/', roles, name='roles'),
    path('add-role/', add_role, name='add-role'),
    path('all-users/', all_users, name='all-users'),
    path('marketers/', marketer_users, name='marketers'),
    path('partners/', partner_users, name='partners'),
    path('admins/', admin_users, name='admins'),
    path('add-user/', add_user, name='add-user'),
    path('coupons/', coupons, name='coupons'),
    path('branch/<slug>/', branch_details, name='branch-details'),
    path('update-role/<id>/', update_role, name='update-role'),
]

handler404 = page_not_found
handler500 = server_error
# handler403 = 'apps.user.views.permission_denied'
handler400 = bad_request

rabito_crm/urls.py
from apps.user.views import permission_error, user_login, user_logout
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from apps.user import urls as user_urls
from apps.patient import urls as patient_urls
from apps.feedback import urls as feedback_urls
from apps.commission import urls as commission_urls
from apps.marketer import urls as marketer_urls
from apps.schedule import urls as schedule_urls
from apps.partner import urls as partner_urls


def layout(request):
    return render(request, 'crm/layout.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include(user_urls, namespace="user")),
    path('patient/', include(patient_urls, namespace="patient")),
    path('feedback/', include(feedback_urls, namespace="feedback")),
    path('commission/', include(commission_urls, namespace="commission")),
    path('marketer/', include(marketer_urls, namespace="marketer")),
    path('partner/', include(partner_urls, namespace="partner")),
    path('planner/', include(schedule_urls, namespace="schedule")),
    path('permission-error/', permission_error, name="permission-error"),
    path('', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

apps/feedback/models.py
from apps.patient.models import Attendance
from django.conf import settings
from django.db import models
from django.utils import timezone
import uuid
# Create your models here.

STATUS = [
    (1, 'Pending'),
    (2, 'Published'),
    (3, 'Unpublished')
]

class Feedback(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    code = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=100, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True, choices=STATUS)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="feedbacks", on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.code)

    class Meta:
        db_table = 'feedback'
        managed = True
        verbose_name = 'Feedback'
        verbose_name_plural = 'Feedbacks'
    

QUESTION_TYPES = [
    ('Radio', 'Radio'),
    ('Scale', 'Scale'),
    ('Rating', 'Rating'),
    ('Fill', 'Fill'),
    ('Choice', 'Choice'),
]

class Question(models.Model):
    feedback_code = models.CharField(max_length=100, blank=True, null=True)
    text = models.CharField(max_length=300, blank=True, null=True)
    is_required = models.BooleanField(default=False, null=True, blank=True)
    question_type = models.CharField(max_length=300, blank=True, null=True, choices=QUESTION_TYPES)
    scale_start_text = models.CharField(max_length=300, blank=True, null=True)
    scale_middle_text = models.CharField(max_length=300, blank=True, null=True)
    scale_end_text = models.CharField(max_length=300, blank=True, null=True)
    scale_count = models.IntegerField(blank=True, null=True)
    choice_answer_one = models.CharField(max_length=300, blank=True, null=True)
    choice_answer_two = models.CharField(max_length=300, blank=True, null=True)
    choice_answer_three = models.CharField(max_length=300, blank=True, null=True)
    choice_answer_four = models.CharField(max_length=300, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="quetions", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.text
    
    class Meta:
        db_table = 'question'
        managed = True
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


class FeedbackResponse(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    attendance = models.ForeignKey(Attendance, blank=True, null=True, related_name='attendance_feedback_response', on_delete=models.DO_NOTHING)
    patient_id = models.CharField(max_length=100, blank=True, null=True)
    officer_id = models.CharField(max_length=100, blank=True, null=True)
    feedback_code = models.CharField(max_length=100, blank=True, null=True)
    is_submitted = models.BooleanField(default=False)
    branch_code = models.CharField(max_length=100, blank=True)
    submitted_by = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="responses", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.feedback_code
    
    class Meta:
        db_table = 'feedback_response'
        managed = True
        verbose_name = 'Feedback Response'
        verbose_name_plural = 'Feedback Responses'
        ordering = ['-created_at']


class Answer(models.Model):
    response = models.ForeignKey(FeedbackResponse, blank=True, null=True, related_name="feedback_response_answer", on_delete=models.DO_NOTHING)
    question = models.ForeignKey(Question, blank=True, null=True, related_name="question_answer", on_delete=models.DO_NOTHING)
    text = models.CharField(max_length=300, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="feedbacks", on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.question)

    class Meta:
        db_table = 'answer'
        managed = True
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'
    

apps/commission/views.py
from apps.user.models import Branch
from apps.commission.models import Commission, CommissionSetup, CommissionStatus
from django.contrib.auth.decorators import login_required
from utils.decorators import crm_required, role_permission_required
from django.shortcuts import redirect, render
from django.contrib import messages
from django.utils import timezone

# Create your views here.

@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commissionsetup", 'permission-error')
def commission_setups(request):

    object_list = CommissionSetup.objects.all()

    context = {
        'object_list': object_list,
        'branches': Branch.objects.all()
    }

    if request.method == 'POST':
        if request.user.role and request.user.role.has_perm('change_commissionsetup'):
            submit = request.POST.get('submit')

            if submit == 'Save':
                
                branch_code = request.POST.get('branch_code')
                figure = request.POST.get('figure')

                try:
                    CommissionSetup.objects.get(branch_code=branch_code)
                    messages.error(request, "Branch already has commission setup")
                    return redirect('commission:setups')
                except:pass

                cs = CommissionSetup.objects.create(
                    branch_code=branch_code,
                    figure=figure,
                    created_by=request.user,
                    commission_type='Flat'
                )

                return redirect('commission:setups')
            elif submit == 'Edit':
                branch_code = request.POST.get('branch_code')
                figure = request.POST.get('figure')
                comm_id = request.POST.get('comm')
                comm = None
                try:
                    comm = CommissionSetup.objects.get(id=comm_id)
                except:
                    messages.error(request, 'Invalid setup selected')
                    return redirect('commission:setups')
                
                comm.branch_code = branch_code
                comm.figure = figure
                comm.modified_by = request.user
                comm.modified_at = timezone.now()

                comm.save()

                return redirect('commission:setups')
                
        else:
            return redirect('permission-error')
        


    return render(request, 'crm/commission_setups.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def all(request):
    object_list = Commission.objects.all()

    context = {
        'object_list': object_list,
    }

    return render(request, 'crm/commissions.html', context)

@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def generated(request):

    object_list = Commission.objects.filter(status=1)

    context = {
        'object_list': object_list,
    }

    if request.method == 'POST':
        print(request.POST)
        comm_ids = request.POST.getlist('commission')
        submit = request.POST.get('submit')
        if submit == 'Confirm':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 2
                        commission.confirmed_by = request.user
                        commission.confirmed_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=2,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully confirmed")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")
        elif submit == 'Cancel':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 4
                        commission.canceled_by = request.user
                        commission.canceled_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=4,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully canceled")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")

        return redirect('commission:generated')

    return render(request, 'crm/generated_commissions.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def confirmed(request):
    object_list = Commission.objects.filter(status=2)

    context = {
        'object_list': object_list,
    }

    if request.method == 'POST':
        print(request.POST)
        comm_ids = request.POST.getlist('commission')
        submit = request.POST.get('submit')
        if submit == 'Approve':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 3
                        commission.approved_by = request.user
                        commission.approved_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=3,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully approved")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")
        elif submit == 'Cancel':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 4
                        commission.canceled_by = request.user
                        commission.canceled_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=4,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully canceled")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")

        return redirect('commission:confirmed')


    return render(request, 'crm/confirmed_commissions.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def approved(request):
    object_list = Commission.objects.filter(status=3)

    context = {
        'object_list': object_list,
    }

    return render(request, 'crm/approved_commissions.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def canceled(request):
    object_list = Commission.objects.filter(status=4)

    context = {
        'object_list': object_list,
    }

    return render(request, 'crm/canceled_commissions.html', context)

templates/crm/admin_users.html
{% extends 'crm/layout.html' %}
{% load crm_tags %}
{% block title %}Admin Users{% endblock title %}
{% block page_title %}Admin Users{% endblock page_title %}
{% block accmenu %}menu-open{% endblock %}
{% block acc %}active{% endblock %}
{% block ad %}active{% endblock %}
{% block content %}
<div class="card">
    <div class="card-header">
        {% if role_perms.change_user %}
        <a href="{% url 'user:add-user' %}?user_type=AD" class="btn btn-default">Add Admin</a>
        {% endif %}

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="example2" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>User Id</th>
                        <th>Full Name</th>
                        <th>Role</th>
                        <th>Email</th>
                        <th>Branch</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    {% branch object.branch_code as branch %}
                    <tr>
                        <td>{{object.code}}</td>
                        <td>{{object.get_full_name}}</td>
                        <td>{{object.role}}</td>
                        <td>{{object.email}}</td>
                        <td>{{branch.description}}</td>
                        <td></td>
                    </tr>
                    {% empty%}
                    <tr>
                        <td colspan="6">Nothing to show here</td>
                    </tr>
                    {% endfor %}
                
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock js %}

templates/crm/canceled_commissions.html
{% extends 'crm/layout.html' %}
{% load crm_tags %}
{% block header %}
<li class="nav-item d-none d-sm-inline-block">
    <a href="{% url 'commission:all' %}" class="nav-link">All</a>
</li>
<li class="nav-item d-none d-sm-inline-block">
    <a href="{% url 'commission:generated' %}" class="nav-link">Generated</a>
</li>
<li class="nav-item d-none d-sm-inline-block">
    <a href="{% url 'commission:confirmed' %}" class="nav-link">Confirmed</a>
</li>
<li class="nav-item d-none d-sm-inline-block">
    <a href="{% url 'commission:approved' %}" class="nav-link">Approved</a>
</li>
<li class="nav-item d-none d-sm-inline-block">
    <a href="{% url 'commission:canceled' %}" class="nav-link active">Canceled</a>
</li>
{% endblock header %}
{% block comm %}active{% endblock %}
{% block title %}Commissions{% endblock title %}
{% block page_title %}Commissions{% endblock page_title %}
{% block content %}
    <div class="card">
        <form action="" method="post">
            <div class="card-header">
                <div class="justify-content-between align-items-center d-flex">
                    <span>Canceled Commissions</span>
                    <div>
                        <!-- <input type="submit" name="submit" value="Approve" class="btn btn-primary">
                        <input type="submit" name="submit" value="Cancel" class="btn btn-warning"> -->
                    </div>
                </div>
                
            </div>{% csrf_token %}
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-borderless">
                        <thead>
                            <tr>
                                <th nowrap>Coupon ID</th>
                                <th nowrap>Partner Code</th>
                                <th nowrap>Patient ID</th>
                                <th nowrap>Amount (GHS)</th>
                                <th nowrap>Branch</th>
                                <th nowrap>Date Canceled</th>
                                <th nowrap>Canceled By</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                                {% partner code=object.partner_code as partner %}
                                {% branch partner.branch_code as branch %}
                                <tr>
                                    
                                    <td nowrap>{{object.coupon_code}}</td>
                                    <td nowrap>{{partner.workplace}}</td>
                                    <td nowrap>{{object.patient_id}}</td>
                                    <td nowrap class="amount" data-index="{{object.amount}}" >{{object.amount}}</td>
                                    <td nowrap>{{ branch.description }}</td>
                                    <td nowrap>{{object.canceled_at}}</td>
                                    <td nowrap>{{object.canceled_by}}</td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="8" align="center">No commissions here</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                Commissions Total: <span class='font-weight-bolder' id="total_comm">GHS 0</span>
            </div>
        </form>
    </div>
{% endblock content %}
{% block js %}
<script>
    let total_comm = 0;
    $(".amount").each(function(index, object) {
        total_comm += parseInt($(this).data('index'));
        $("#total_comm").html("GHS "+total_comm);
    });
</script>
{% endblock js %}

templates/crm/feedback_responses.html
{% extends 'crm/layout.html' %}
{% load crm_tags %}
{% block title %}Feedback Responses{% endblock title %}
{% block page_title %}Feedback Responses{% endblock page_title %}
{% block resp %}active{% endblock resp %}
{% block content %}
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table-striped table-hover table">
                <thead>
                    <tr>
                        <th>Patient</th>
                        <th>Attendance Date</th>
                        <th>Feedback Setup</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        {% patient object.patient_id as patient %}
                        {% feedback_setup object.feedback_code as feedback %}
                        <tr>
                            <td>{{patient.full_name}}</td>
                            <td>{{object.attendance.created_at}}</td>
                            <td>{{feedback.description}}</td>
                            <td>
                                {% if object.is_submitted %}
                                Submitted
                                {% else %}
                                Not Submitted
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'feedback:response-details' object.uuid %}" class="btn btn-default btn-sm">
                                    <i class="fa fa-paper-plane fa-1x"></i>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">No feedback response</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/crm/feedback_setup.html
{% extends 'crm/layout.html' %}
{% block setmenu %}menu-open{% endblock %}
{% block set %}active{% endblock set %}
{% block feeds %}active{% endblock feeds %}
{% block title %}Feedback Setup{% endblock title %}
{% block page_title %}Feedback Setup{% endblock page_title %}
{% block content %}
<div class="card">
    <div class="card-header">
    {% if role_perms.change_feeback %}
    <a href="{% url 'feedback:add-setup' %}" class="btn btn-default">Add Feedback Setup</a>
    {% endif %}
        
    </div>
    <div class="card-body">
        <div class="list-group-flush">
            {% for object in object_list %}
                <a href="{% url 'feedback:setup-details' object.uuid %}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ object.description }}</h5>
                        <small class="text-muted">{{object.created_at }}</small>
                    </div>
                    <!-- <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius
                        blandit.</p> -->
                    <small class="text-muted">{{object.get_status_display }}</small>
                </a>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock content %}

templates/crm/roles.html
{% extends 'crm/layout.html' %}
{% block setmenu %}menu-open{% endblock %}
{% block set %}active{% endblock set %}
{% block roles %}active{% endblock %}
{% block title %}User Roles{% endblock title %}
{% block page_title %}User Roles{% endblock page_title %}
{% block content %}
<div class="card">
    <div class="card-header">
    {% if role_perms.change_role %}
    <a href="{% url 'user:add-role' %}" class="btn btn-default">Add Role</a>
    {% endif %}
    
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th nowrap="nowrap">Role</th>
                        <th nowrap="nowrap">Permissions</th>
                        <th nowrap>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for role in object_list %}
                        <tr>
                            <td>{{ role.description }}</td>
                            <td width="50%" class="text-wrap">
                                {% for perm in role.permissions.all  %}
                                    {{ perm.name }},                       
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'user:update-role' role.id %}" class="btn btn-primary">Update</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/crm/search_patients.html
{% extends 'crm/layout.html' %}
{% load crm_tags %}
{% block pat %}active{% endblock pat %}
{% block title %}Search Patient{% endblock title %}
{% block page_title %}{% endblock page_title %}
{% block content %}
<h2 class="text-center display-4">Search Patient</h2>
<div class="row">
    <div class="col-md-8 col-lg-8 offset-md-2 offset-lg-1">
        <form action="">
            <div class="input-group">
                <input value="{{search}}" type="search" required autocomplete="off" class="form-control form-control-lg" name="search"
                    placeholder="Search by first name, last name, phone number, patient id or date of birth (YYYY-MM-DD)">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-lg btn-default">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-4 col-lg-2">
        <a href="{% url 'patient:add' %}" class="btn btn-lg btn-primary"><i class="fa fa-plus"></i></a>
        <a href="{% url 'patient:all' %}" class="btn btn-lg btn-dark"><i class="fa fa-tasks"></i></a>
    </div>

</div>

{% if object_list != None %}
<div class="row mt-3">
    <div class="col-md-10 offset-md-1">
        <div class="list-group">
            {% for object in object_list %}
            <div class="list-group-item">
                <div class="row">
                    <div class="col px-4">
                        <div>
                            <div class="float-right">Date of Bith: {{object.date_of_birth}}</div>
                            <a href="{% url 'patient:details' object.uuid %}" class="h3">{{object.full_name}}</a>
                            <ul class="list-unstyled">
                                <li>
                                    <a href="{% url 'patient:details' object.uuid %}" class="btn-link text-secondary"><i class="far fa-fw fa-id-badge"></i>
                                        {{object.code}}</a>
                                </li>
                                <li>
                                    <a href="" class="btn-link text-secondary"><i class="fa fa-fw fa-phone"></i>
                                        {{object.phone_number}}</a>
                                </li>
                                <li>
                                    <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-envelope"></i>
                                        {{object.email}}</a>
                                </li>
                                <li>
                                    <a href="" class="btn-link text-secondary"><i class="fa fa-fw fa-code-branch "></i>
                                        {% branch object.branch_code as branch %}
                                        {{branch.description}}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="list-group-item">
                <div class="row">
                    <div class="col px-4">
                        <div>
                            <!-- <div class="float-right">2021-04-20 04:04pm</div> -->
                            <h3>Nothing found</h3>
                            <p class="mb-0">Search term did not match any records.</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endif %}

{% endblock content %}