apps/commission/urls.py
from django.urls import path

from . views import *

app_name = 'commissiion'

urlpatterns = [
    path('setups/', commission_setups, name='setups'),
    path('', all, name='all'),
    path('generated/', generated, name='generated'),
    path('confirmed/', confirmed, name='confirmed'),
    path('approved/', approved, name='approved'),
    path('canceled/', canceled, name='canceled'),
]

apps/partner/urls.py
from django.urls import path
from .views import *

app_name = 'partner'


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('coupons/', coupons, name='coupons'),
    path('commissions/', commissions, name='commissions'),
    path('coupons-search/', search_coupons, name='coupons_search')
]

rabito_crm/urls.py
from apps.user.views import permission_error, user_login, user_logout
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from apps.user import urls as user_urls
from apps.patient import urls as patient_urls
from apps.feedback import urls as feedback_urls
from apps.commission import urls as commission_urls
from apps.marketer import urls as marketer_urls
from apps.schedule import urls as schedule_urls
from apps.partner import urls as partner_urls


def layout(request):
    return render(request, 'crm/layout.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include(user_urls, namespace="user")),
    path('patient/', include(patient_urls, namespace="patient")),
    path('feedback/', include(feedback_urls, namespace="feedback")),
    path('commission/', include(commission_urls, namespace="commission")),
    path('marketer/', include(marketer_urls, namespace="marketer")),
    path('partner/', include(partner_urls, namespace="partner")),
    path('planner/', include(schedule_urls, namespace="schedule")),
    path('permission-error/', permission_error, name="permission-error"),
    path('', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

apps/feedback/models.py
from apps.patient.models import Attendance
from django.conf import settings
from django.db import models
from django.utils import timezone
import uuid
# Create your models here.

STATUS = [
    (1, 'Pending'),
    (2, 'Published'),
    (3, 'Unpublished')
]

class Feedback(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    code = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=100, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True, choices=STATUS)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="feedbacks", on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.code)

    class Meta:
        db_table = 'feedback'
        managed = True
        verbose_name = 'Feedback'
        verbose_name_plural = 'Feedbacks'
    

QUESTION_TYPES = [
    ('Radio', 'Radio'),
    ('Scale', 'Scale'),
    ('Rating', 'Rating'),
    ('Fill', 'Fill'),
    ('Choice', 'Choice'),
]

class Question(models.Model):
    feedback_code = models.CharField(max_length=100, blank=True, null=True)
    text = models.CharField(max_length=300, blank=True, null=True)
    is_required = models.BooleanField(default=False, null=True, blank=True)
    question_type = models.CharField(max_length=300, blank=True, null=True, choices=QUESTION_TYPES)
    scale_start_text = models.CharField(max_length=300, blank=True, null=True)
    scale_middle_text = models.CharField(max_length=300, blank=True, null=True)
    scale_end_text = models.CharField(max_length=300, blank=True, null=True)
    scale_count = models.IntegerField(blank=True, null=True)
    choice_answer_one = models.CharField(max_length=300, blank=True, null=True)
    choice_answer_two = models.CharField(max_length=300, blank=True, null=True)
    choice_answer_three = models.CharField(max_length=300, blank=True, null=True)
    choice_answer_four = models.CharField(max_length=300, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="quetions", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.text
    
    class Meta:
        db_table = 'question'
        managed = True
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


class FeedbackResponse(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    attendance = models.ForeignKey(Attendance, blank=True, null=True, related_name='attendance_feedback_response', on_delete=models.DO_NOTHING)
    patient_id = models.CharField(max_length=100, blank=True, null=True)
    officer_id = models.CharField(max_length=100, blank=True, null=True)
    feedback_code = models.CharField(max_length=100, blank=True, null=True)
    is_submitted = models.BooleanField(default=False)
    branch_code = models.CharField(max_length=100, blank=True)
    submitted_by = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="responses", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.feedback_code
    
    class Meta:
        db_table = 'feedback_response'
        managed = True
        verbose_name = 'Feedback Response'
        verbose_name_plural = 'Feedback Responses'
        ordering = ['-created_at']


class Answer(models.Model):
    response = models.ForeignKey(FeedbackResponse, blank=True, null=True, related_name="feedback_response_answer", on_delete=models.DO_NOTHING)
    question = models.ForeignKey(Question, blank=True, null=True, related_name="question_answer", on_delete=models.DO_NOTHING)
    text = models.CharField(max_length=300, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="feedbacks", on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.question)

    class Meta:
        db_table = 'answer'
        managed = True
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'
    

apps/commission/views.py
from apps.user.models import Branch
from apps.commission.models import Commission, CommissionSetup, CommissionStatus
from django.contrib.auth.decorators import login_required
from utils.decorators import crm_required, role_permission_required
from django.shortcuts import redirect, render
from django.contrib import messages
from django.utils import timezone

# Create your views here.

@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commissionsetup", 'permission-error')
def commission_setups(request):

    object_list = CommissionSetup.objects.all()

    context = {
        'object_list': object_list,
        'branches': Branch.objects.all()
    }

    if request.method == 'POST':
        if request.user.role and request.user.role.has_perm('change_commissionsetup'):
            submit = request.POST.get('submit')

            if submit == 'Save':
                
                branch_code = request.POST.get('branch_code')
                figure = request.POST.get('figure')

                try:
                    CommissionSetup.objects.get(branch_code=branch_code)
                    messages.error(request, "Branch already has commission setup")
                    return redirect('commission:setups')
                except:pass

                cs = CommissionSetup.objects.create(
                    branch_code=branch_code,
                    figure=figure,
                    created_by=request.user,
                    commission_type='Flat'
                )

                return redirect('commission:setups')
            elif submit == 'Edit':
                branch_code = request.POST.get('branch_code')
                figure = request.POST.get('figure')
                comm_id = request.POST.get('comm')
                comm = None
                try:
                    comm = CommissionSetup.objects.get(id=comm_id)
                except:
                    messages.error(request, 'Invalid setup selected')
                    return redirect('commission:setups')
                
                comm.branch_code = branch_code
                comm.figure = figure
                comm.modified_by = request.user
                comm.modified_at = timezone.now()

                comm.save()

                return redirect('commission:setups')
                
        else:
            return redirect('permission-error')
        


    return render(request, 'crm/commission_setups.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def all(request):
    object_list = Commission.objects.all()

    context = {
        'object_list': object_list,
    }

    return render(request, 'crm/commissions.html', context)

@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def generated(request):

    object_list = Commission.objects.filter(status=1)

    context = {
        'object_list': object_list,
    }

    if request.method == 'POST':
        print(request.POST)
        comm_ids = request.POST.getlist('commission')
        submit = request.POST.get('submit')
        if submit == 'Confirm':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 2
                        commission.confirmed_by = request.user
                        commission.confirmed_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=2,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully confirmed")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")
        elif submit == 'Cancel':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 4
                        commission.canceled_by = request.user
                        commission.canceled_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=4,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully canceled")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")

        return redirect('commission:generated')

    return render(request, 'crm/generated_commissions.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def confirmed(request):
    object_list = Commission.objects.filter(status=2)

    context = {
        'object_list': object_list,
    }

    if request.method == 'POST':
        print(request.POST)
        comm_ids = request.POST.getlist('commission')
        submit = request.POST.get('submit')
        if submit == 'Approve':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 3
                        commission.approved_by = request.user
                        commission.approved_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=3,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully approved")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")
        elif submit == 'Cancel':
            if comm_ids:
                for comm in comm_ids:
                    try:
                        commission = Commission.objects.get(coupon_code=comm)
                        commission.status = 4
                        commission.canceled_by = request.user
                        commission.canceled_at = timezone.now()
                        commission.save()
                        CommissionStatus.objects.create(
                            commission=commission,
                            status=4,
                            created_by=request.user
                        )
                        messages.success(request, f"Commission with ID {comm} successfully canceled")
                    except Commission.DoesNotExist:
                        messages.error(request, f"Commission with ID {comm} does not exist")
            else:
                messages.info(request, f"Please select at least one commission")

        return redirect('commission:confirmed')


    return render(request, 'crm/confirmed_commissions.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def approved(request):
    object_list = Commission.objects.filter(status=3)

    context = {
        'object_list': object_list,
    }

    return render(request, 'crm/approved_commissions.html', context)


@login_required(login_url='login')
@crm_required(redirect_url='permission-error')
@role_permission_required("view_commission", 'permission-error')
def canceled(request):
    object_list = Commission.objects.filter(status=4)

    context = {
        'object_list': object_list,
    }

    return render(request, 'crm/canceled_commissions.html', context)

templates/partners/commissions.html
{% extends 'partners/layout.html' %}
{% block title %}Commissions{% endblock title %}
{% block page_title %}Commissions{% endblock page_title %}
{% block comm %}active{% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <form action="" method="get">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <input type="text" name="coupon" value="{{coupon}}" id="coupon_id" placeholder="Coupon Code" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <input type="text" name="start" value="{{start|safe}}" autocomplete="off" required id="start" placeholder="Start Date"
                                class="form-control form-control-sm datetimepicker-input" data-toggle="datetimepicker"
                                data-target="#start" />
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <input type="text" name="end" value="{{end | safe}}" autocomplete="off" required id="end" placeholder="End Date"
                                class="form-control form-control-sm datetimepicker-input" data-toggle="datetimepicker"
                                data-target="#end" />
                        </div>
                    </div>
                    <div class="col">
                        <input type="submit" value="Filter" name="submit" class="btn btn-info btn-sm">
                        <a href="{% url 'partner:commissions' %}" class="btn btn-dark btn-sm">Reset</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th>Coupon Code</th>
                            <th>Amount (GHS)</th>
                            <!-- <th>Status</th> -->
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in page_obj %}
                        <tr>
                            <td>{{object.coupon_code}}</td>
                            <td>{{object.amount}}</td>
                            {% comment %} <td>{{object.get_status_display}}</td> {% endcomment %}
                            <td>{{object.created_at}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Total</th>
                            <th>{{total}}</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div class="card-footer clearfix">
            <span>Showing {{page_obj.start_index}}-{{page_obj.end_index}}  of {{object_count}} Records</span>
            
            <ul class="pagination pagination-sm m-0 float-right">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?coupon={{coupon}}&start={{start|safe}}&end={{end|safe}}&page=1">&laquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?coupon={{coupon}}&start={{start|safe}}&end={{end|safe}}&page={{page_obj.previous_page_number}}">1</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" disabled aria-disabled="true" href="#">&laquo;</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" disabled href="#">{{page_obj.number}}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?coupon={{coupon}}&start={{start|safe}}&end={{end|safe}}&page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
                    <li class="page-item"><a class="page-link" href="?coupon={{coupon}}&start={{start|safe}}&end={{end|safe}}&page={{page_obj.next_page_number}}">&raquo;</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" disabled aria-disabled="true" href="#">&raquo;</a></li>
                {% endif %}
                <!-- <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li> -->
            </ul>
          </div>
    </div>
</div>
{% endblock content %}
{% block js %}
<script>
    $(function () {
        $('[data-mask]').inputmask()
        //Date picker
        $('#start').datetimepicker({
            format: 'YYYY-MM-DD'
        });
        $('#end').datetimepicker({
            format: 'YYYY-MM-DD'
        });
        $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });
    });
</script>
{% endblock js %}

templates/partners/coupons.html
{% extends 'partners/layout.html' %}
{% block title %}Coupons{% endblock title %}
{% block page_title %}Coupons{% endblock page_title %}
{% block coups %}active{% endblock coups %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <a href="" class="btn btn-default" data-toggle="modal" data-target="#newCoupon">Generate Coupon</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Date of Birth</th>
                            <th>Phone Number</th>
                            <th>Commission Due (GHS)</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td>{{object.code}}</td>
                            <td>{{object.patient_first_name}}</td>
                            <td>{{object.patient_last_name}}</td>
                            <td>{{object.patient_dob}}</td>
                            <td>{{object.patient_phone_number}}</td>
                            <td>{{object.commission}}</td>
                            <td>{{object.get_status_display}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="newCoupon" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Enter Patient Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="id_first">First Name</label>
                        <input type="text" name="first_name" required placeholder="First Name" id="id_first"
                            class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_last">Last Name</label>
                        <input type="text" name="last_name" required placeholder="Last Name" id="id_last"
                            class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_phone">Phone Number</label>
                        <input type="text" name="phone_number" required placeholder="Phone Number" id="id_phone"
                            class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_dob">Date of Birth</label>
                        <input type="text" name="dob" required placeholder="Date of Birth" id="id_dob"
                            class="form-control datetimepicker-input" data-toggle="datetimepicker"
                            data-target="#id_dob">
                    </div>
                    <small>Coupons are awarded when details match patients records sent to us</small>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Generate Coupon</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
<script>
    $(function () {
        $('[data-mask]').inputmask()
        //Date picker
        $('#id_dob').datetimepicker({
            format: 'YYYY-MM-DD'
        });
        $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });
    });

</script>
{% endblock js %}

templates/partners/dashboard.html
{% extends 'partners/layout.html' %}
{% block title %}Dashboard{% endblock title %}
{% block page_title %}Dashboard{% endblock page_title %}
{% block dash %}active{% endblock dash %}

templates/partners/layout.html
{% load static %}
{% load crm_tags %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Rabito Partner</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static '' %}plugins/toastr/toastr.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>

<body class="hold-transition layout-top-nav layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
            <div class="container">
                <a href="{% url 'partner:dashboard' %}" title="Rabito Partner" class="navbar-brand {% block dash %}{% endblock %}">
                    <img src="{% static 'dist/img/rabito-icon.png' %}" alt="rabito Logo"
                        class="brand-image img-circle elevation-3" style="opacity: .8">
                    <span class="brand-text font-weight-light">{% partner user as partner%} {{partner.workplace}}</span>
                </a>

                <button class="navbar-toggler order-1" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    <!-- Left navbar links -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'partner:coupons' %}" class="nav-link {% block coups %}{% endblock %}">Coupons</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'partner:commissions' %}" class="nav-link {% block comm%}{% endblock %}">Commissions</a>
                        </li>
                        
                    </ul>
                </div>

                <!-- Right navbar links -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    <li class="nav-item">
                        <a href="#" class="nav-link">{{user.get_full_name}}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{%url 'logout'%}" class="nav-link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- /.navbar -->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">{% block page_title %}Page Title{% endblock %}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <!-- <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Layout</a></li>
                                <li class="breadcrumb-item active">Top Navigation</li>
                            </ol> -->
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    {% block content %}
                      
                    {% endblock content %}
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Rabito CRM
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2014-2021 <a href="">Moon Labs</a>.</strong> All rights
            reserved.
        </footer>
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- InputMask -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'plugins/inputmask/jquery.inputmask.min.js' %}"></script>
    <!-- date-range-picker -->
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <script src="{% static '' %}plugins/toastr/toastr.min.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- <script src="../../dist/js/demo.js"></script> -->
    {% block js %}{% endblock js %}
    <script>
    // var Toast = Swal.mixin({
    //   toast: true,
    //   position: 'top-end',
    //   showConfirmButton: true,
    //   timer: 10000
    // });
    {% if messages %}
    {% for message in messages %}
    // Toast.fire({
    //     icon: '{{message.tags}}',
    //     title: '{{message}}'
    //   })
    toastr.{{message.tags}}('{{message}}')
    {% endfor %}
    {% endif %}
      
    
    </script>
</body>

</html>